package com.example.musicplayer.mdreader

import java.io.BufferedInputStream
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileInputStream
import java.text.ParseException
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale
import kotlin.math.min

abstract class MarkdownReaderBase {

    // Regex pattern developed by Islam Kertov, thanks bro!
    // It analyze yaml front matter in markdown. Returns key in group 1 and value in group 2
    protected var frontMatterRegex = Regex(
        pattern = "(^\\w*[^: \\[\\]]): ?([\\w\\S': ]*)$",
        option = RegexOption.MULTILINE
    )
    protected var frontMatterDashesRegex = Regex(
        pattern = "^---\n",
        option = RegexOption.MULTILINE
    )
    protected var frontMatterListRegex = Regex(
        pattern = "^\\s+-\\s+(?:\"([^\"]*)\"|'([^']*)'|(?!\\[\\[)([^\\r\\n]+?))\\s*$",
        option = RegexOption.MULTILINE
    )

    protected val yamlListIndent = "  - "


    protected open fun readFile(file: File): String {
        // Generated by Perplexity
        var result = ""
        ByteArrayOutputStream().use { buffer ->
            FileInputStream(file).use { inputStream ->
                BufferedInputStream(inputStream).use { bis ->
                    val data = ByteArray(4096)
                    var bytesRead: Int
                    while (bis.read(data, 0, data.size).also { bytesRead = it } != -1) {
                        buffer.write(data, 0, bytesRead)
                    }
                }
            }
            result = buffer.toString(Charsets.UTF_8.name())
        }
        return result
    }

    protected open fun saveMarkdown(file: File, yamlMap: Map<String, String>) {
        var text = readFile(file)
        if (!text.startsWith("---\n"))
            text = "---\n---\n\n$text"

        var endIndex = frontMatterDashesRegex
            .findAll(text)
            .iterator()
            .next()
            .next()?.range?.start ?: 0

        // Phase 1: add missing keys
        for ((key, value) in yamlMap) {
            if (!text.contains("$key:") || text.indexOf("$key:") > endIndex) {
                val block = if (value.startsWith(yamlListIndent)) {
                    "$key:\n$value\n"
                } else {
                    "$key: $value\n"
                }
                text = text.substring(0, endIndex) + block + text.substring(endIndex)
                endIndex = frontMatterDashesRegex
                    .findAll(text)
                    .iterator()
                    .next()
                    .next()?.range?.start ?: 0
            }
        }

        // Phase 2: replace existing values
        var matches = frontMatterRegex.findAll(text).toList()
        for (match in matches) {
            if (match.range.first > endIndex)
                break

            val line = match.groups[0]!!.value
            val key = match.groups[1]!!.value
            if (key !in yamlMap)
                continue

            val value = yamlMap[key]!!
            if (value.startsWith(yamlListIndent)) {
                val nextMatch = frontMatterRegex.find(text, startIndex = match.range.last + 2)
                val nextStart = nextMatch?.range?.first ?: endIndex
                text = text.replaceRange(
                    startIndex = match.range.first,
                    endIndex = min(nextStart, endIndex),
                    replacement = "$key:\n$value\n",
                )
                endIndex = frontMatterDashesRegex
                    .findAll(text)
                    .iterator()
                    .next()
                    .next()?.range?.start ?: 0
            } else {
                text = text.replaceFirst(line, "$key: $value")
            }
        }
        file.writeText(text = text)
    }

    protected open fun parseYamlFrontMatter(markdownContent: String): Map<String, String> {
        val yamlMap = mutableMapOf<String, String>()
        if (!markdownContent.startsWith("---\n"))
            return yamlMap

        val endIndex = frontMatterDashesRegex
            .findAll(markdownContent)
            .iterator()
            .next()
            .next()?.range?.start ?: 0

        val matches = frontMatterRegex.findAll(markdownContent)
        for (match in matches) {
            if (match.range.first !in 0..endIndex)
                break

            // 0-line 1-key 2-value
            val key = match.groups[1]!!.value
            var value = match.groups[2]!!.value
            if (value.isEmpty()) {
                val listStartIndex = match.groups[2]!!.range.last + 1
                val listEndIndex = (frontMatterRegex.find(
                    input = markdownContent,
                    startIndex = listStartIndex,
                )?.range?.start) ?: endIndex

                value = markdownContent.substring(
                    startIndex = listStartIndex,
                    endIndex = min(listEndIndex, endIndex),
                ).trim('\n')
            }
            yamlMap[key] = value
        }
        return yamlMap
    }

    open fun toLink(str: String): String {
        val result = str.removeSurrounding("\"")
        return if (result.isNotEmpty()) "\"[[$result]]\"" else "\"$result\""
    }

    open fun unLink(str: String): String {
        return str
            .removePrefix("\"").removePrefix("[[")
            .removeSuffix("\"").removeSuffix("]]")
    }


    open fun getDateFromString(source: String): Calendar {
        val date = try {
            if (source.isNotEmpty()) {
                SimpleDateFormat(
                    "yyyy-MM-dd HH:mm:ss",
                    Locale.getDefault()
                ).parse(source)
            } else {
                Date()
            }
        } catch (_: ParseException) {
            try {
                SimpleDateFormat(
                    "yyyy-MM-dd'T'HH:mm:ssXXX",
                    Locale.getDefault()
                ).parse(source)
            } catch (_: ParseException) {
                SimpleDateFormat(
                    "yyyy-MM-dd'T'HH:mm:ss",
                    Locale.getDefault()
                ).parse(source)
            }
        }
        return Calendar
            .Builder()
            .setInstant(date)
            .build()
    }

    // String array is type YAML list:
    //  - "value1"
    //  - "value2"
    open fun stringArrayToList(str: String): List<String> {
        val result = mutableListOf<String>()
        val matches = frontMatterListRegex.findAll(str)
        for (match in matches) {
            val el = match.groups[1]?.value
                ?: match.groups[2]?.value
                ?: match.groups[3]?.value
                ?: ""
            result.add(el)
        }
        return result
    }

    /**
     * Return YAML list. If list is empty return "[]".
     *
     * Example:
     *   - "value1"
     *   - 'value2 "123"'
     *   - "[[wiki link]]"
     */
    open fun toYamlList(list: List<String>): String {
        if (list.isEmpty()) {
            return "[]"
        }

        return list.joinToString("\n") {
            val escape = if (it.removeSurrounding("\"").contains("\""))
                '\'' else '"'
            "$yamlListIndent$escape${it.removeSurrounding("\"")}$escape"
        }
    }
}